/*MySQL Syntax*/
CREATE TABLE RESERVATIONS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  clientFullName VARCHAR(200) UNIQUE,
  roomNumber INT,
  reservationDates JSON
);

CREATE TABLE THEATRES (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) UNIQUE,
  address VARCHAR(200) ,
  city VARCHAR(40) ,
  state VARCHAR(40) ,
  country VARCHAR(40)
);

CREATE TABLE SALAS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  idEvento int,
  status VARCHAR(60),
  asientosMapa VARCHAR(200)
);

CREATE TABLE USERS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) ,
  email VARCHAR(70) UNIQUE,
  cellPhone VARCHAR(20) ,
  status VARCHAR(20)
);


CREATE TABLE PAYMENTS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  amount FLOAT(200) ,
  timestamp VARCHAR(70) ,
  tipoPago VARCHAR(50) ,
  description VARCHAR(70),
  referenceDetails VARCHAR(70),
  status varchar(20)
);

CREATE TABLE EVENTS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tipoEvento VARCHAR(50) ,
  nombreEvento VARCHAR(50) ,
  horarioInicio VARCHAR(50) ,
  horarioFin VARCHAR(50) ,
  audioIdiomaEvento VARCHAR(50),
  subtitulosIdiomaEvento VARCHAR(50),
  classification VARCHAR(50),
  comments VARCHAR(50)
);

CREATE TABLE BOOKINGS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  idTheatre INT,
  idSala INT,
  idUsuario INT,
  idPayment INT,
  comments VARCHAR(50),
  status  VARCHAR(50)
);

/*
CREATE TABLE RESERVATIONS (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 200, INCREMENT BY 1) PRIMARY KEY,
    clientFullName VARCHAR(200),
    roomNumber int,
    reservationDates varchar(200)
);
*/